# Generated by Django 6.0.1 on 2026-01-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram')], max_length=20)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_user_id', models.CharField(help_text='IG User ID', max_length=100)),
                ('page_id', models.CharField(help_text='FB Page ID connected to IG', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'external_user_id')},
            },
        ),
    ]
