# Generated by Django 6.0.1 on 2026-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
