# Generated by Django 4.2.27 on 2026-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='base_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkedin_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkedin_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
